CREATE TABLE IF NOT EXISTS "waitlist_signups" (
  "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "email" text NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "waitlist_signups_email_unique" UNIQUE ("email")
);
